twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        image_article_coverage_directory: '%image_articles_coverages_directory%'
        image_article_coverage_display: '%image_articles_coverages_display%'
        notifications: '@App\Twig\NotificationExtension'
        usersConversations: '@App\Twig\UserExtension'
        mercure_publish_url: '%env(MERCURE_PUBLISH_URL)%'

when@test:
    twig:
        strict_variables: true
